"""Fix Product-Inventory relationship

Revision ID: 6732061cf7a1
Revises: 14dcb88c2b3f
Create Date: 2025-02-07 05:21:18.568002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6732061cf7a1'
down_revision: Union[str, None] = '14dcb88c2b3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
